export default {
    fire: require('../assets/fire.png'),
    conversation: require('../assets/conversation.png'),
    check: require('../assets/check.png'),
    wireless: require('../assets/wireless.png'),
    library: require('../assets/book.png'),
    facebook: require('../assets/facebook.png'),
    google: require('../assets/google-plus.png'),
    shopee: require('../assets/shopee.png'),
    lazada: require('../assets/lazada.png'),
    menu: require('../assets/menu.png'),
    search: require('../assets/loupe.png'),
    heart: require('../assets/heart.png'),
    vote: require('../assets/pinkStar.png'),
    rate: require('../assets/star.png'),
}